## Path to TSV file containing sample information (required columns: sample)
samples: "config/samples.tsv"
## Path to TSV file containing sequencing unit information (required columns: sample, unit, fq1, fq2)
units: "config/units.tsv"

## Path to raw data specified in units.tsv
data_dir: "../raw_data"

ref:
  ## Ensembl species name
  species: homo_sapiens
  ## Emsembl release
  release: 112
  ## Genome build
  build: GRCh38

## Read length of raw FASTQ data
## Used for calculating the maximum possible overhang for reads across splice junctions
## (i.e. for STAR's --sjdbOverhang paramter)
read_length: 150

## FastQC configuration
fastqc:
  ## Boolean specifying whether FastQC output is desired
  activate: True
  extra: "--noextract"

## fastp configuration
trim:
  ## Single-end
  extra_se: "--qualified_quality_phred 20 --length_required 35 --trim_poly_g"
  ## Paired-end
  extra_pe: "--detect_adapter_for_pe --qualified_quality_phred 20 --length_required 35 --trim_poly_g"

## STAR configuration
align:
  ## Keep BAM files or automatically delete them
  keep_bam: True
  ## The align rule is configured to specify STAR's --sjdbOverhang parameter using the read_length defined above
  ## Specify any further parameters here
  extra: "--outSAMtype BAM SortedByCoordinate"

## UMI-tools configuration
deduplicate:
  ## Boolean to specify whether alignments should be deduplicated by UMI and position
  activate: False
  ## Extra params passed to UMI-tools
  extra: "--paired --umi-separator=:"

## featureCounts configuration
featureCounts:
  ## Specify as True to produce gene-level counts
  activate: True
  ## Strandedness of the library, passed to the -s option
  ## 0: unstranded, 1: stranded, and 2: reversely stranded
  ## Requires a list. Multiple choices can be specified if the strandedness is unknown, producing a featureCounts output for each
  strandedness: [0, 1, 2]
  ## -p indicates the BAM files contain paired-end data, omit this flag for single-end
  ## --countReadPairs count read pairs (fragments) instead of reads. Only required for paired end data. This was introduced in subread v2.0.2
  extra: "-p --countReadPairs"

## Salmon configuration
salmon:
  ## Specify as True to produce transcript-level counts
  activate: True
  index:
    ## Extra params passed to salmon index
    extra: ""
  quant:
    ## Library type
    ## "A" allows Salmon to automatically infer the library type
    libtype: "A"
    ## Extra params passed to salmon quant
    extra: ""
